import pygame

# Constants

WORLD_WIDTH = 0
WORLD_HEIGHT = 0

SCREEN_WIDTH = 0
SCREEN_HEIGHT = 0
SCREEN_ASPECT_RATIO = 0

SCREEN_TO_WORLD_RATIO = 0

def init() -> None:
    global WORLD_WIDTH, WORLD_HEIGHT, SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_ASPECT_RATIO, SCREEN_TO_WORLD_RATIO

    info = pygame.display.Info()

    SCREEN_WIDTH = info.current_w 
    SCREEN_HEIGHT = info.current_h
    SCREEN_ASPECT_RATIO = SCREEN_WIDTH / SCREEN_HEIGHT

    WORLD_WIDTH = 1
    WORLD_HEIGHT = 1 / SCREEN_ASPECT_RATIO

    SCREEN_TO_WORLD_RATIO = SCREEN_WIDTH / WORLD_WIDTH

def world_to_screen(x, y):
    return (x * SCREEN_TO_WORLD_RATIO, y * SCREEN_TO_WORLD_RATIO)

